apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bchSmilesToStructures.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.bchSmilesToStructures.Name }}
  template: 
    metadata:
      labels:
        app: {{ .Values.bchSmilesToStructures.Name }}
    spec:
      containers:
      - name: bch-enzymeml
        image: stephan211087/{{ .Values.bchSmilesToStructures.ContainerName }}
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bchSmilesToStructures.ServiceName }}
spec:
  selector:
    app: {{ .Values.bchSmilesToStructures.Name }}
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000