apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressSpecs.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
spec:

  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - retrobiohub.org
    secretName: letsencrypt-staging  # < name of the secret in which the keys will be stored
    #secretName: {{ .Values.ingress.TLSSecretName }} # < name of the secret in which the keys will be stored
  defaultBackend:
    service:
      name: {{ .Values.frontend.ServiceName }}
      port:
        number: 80
  rules:
  - host: retrobiohub.org
    http:
      paths:
      # Path definition Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.ServiceName }}
            port:
              number: 80
      # Path definition Retrobiohub
      - path: /retrobiohub
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.retrobiohub.ServiceName }}
            port:
              number: 5000
      # path definition of enzymeml
      - path: /enzml
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.bchEnzml.ServiceName }}
            port:
              number: 5000
      - path: /smiles
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.bchSmilesToStructures.ServiceName }}
            port:
              number: 5000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.bchDbQuery.ServiceName }}
            port:
              number: 5000

 