apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.Name }}
  template: 
    metadata:
      labels:
        app: {{ .Values.frontend.Name }}
    spec:
      containers:
      - name: {{ .Values.frontend.Name }}
        image: stephan211087/biocat-example:verror8
        #image: stephan211087/frontend-retrobiohub:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.ServiceName }}
spec:
  selector:
    app: {{ .Values.frontend.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
